### ISSUE TITLE
video intelligence samples failing with updated gems

### ISSUE THREAD

**Issue by dizcology** [GoogleCloudPlatform/ruby-docs-samples#496]
To reproduce (in Ruby 2.4.7):

Tests pass:
```
bundle install
bundle exec rspec spec/quickstart_spec.rb
```

Tests fail:
```
bundle update
bundle exec rspec spec/quickstart_spec.rb
```

Error message:
```
Failures:

  1) Video Intelligence API Quickstart can find labels for a cat video
     Failure/Error: load File.expand_path("../quickstart.rb", __dir__)
     
     ArgumentError:
       Expected array as initializer value for repeated field 'features' (given Hash).
     # /usr/local/bundle/gems/google-gax-1.8.1/lib/google/gax/util.rb:64:in `initialize'
     # /usr/local/bundle/gems/google-gax-1.8.1/lib/google/gax/util.rb:64:in `new'
     # /usr/local/bundle/gems/google-gax-1.8.1/lib/google/gax/util.rb:64:in `to_proto'
     # /usr/local/bundle/gems/google-cloud-video_intelligence-2.0.2/lib/google/cloud/video_intelligence/v1/video_intelligence_service_client.rb:291:in `annotate_video'
     # ./quickstart.rb:23:in `<top (required)>'
     # ./spec/quickstart_spec.rb:20:in `load'
     # ./spec/quickstart_spec.rb:20:in `block (3 levels) in <top (required)>'
     # ./spec/quickstart_spec.rb:19:in `block (2 levels) in <top (required)>'
```

I tried to update only google-protobuf and the test would pass.
